import os


# =========================
# GEMINI SUPPORT
# =========================
def ask_gemini(prompt):
    import google.generativeai as genai

    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        return None

    genai.configure(api_key=api_key)

    model = genai.GenerativeModel("gemini-2.5-flash")

    try:
        response = model.generate_content(prompt)

        # Safe access to response.text
        try:
            if response.text:
                return response.text
        except Exception:
            pass

        # Fallback: read candidate parts
        if hasattr(response, "candidates") and response.candidates:
            candidate = response.candidates[0]

            if (
                hasattr(candidate, "content")
                and candidate.content
                and hasattr(candidate.content, "parts")
                and candidate.content.parts
            ):
                text = ""

                for part in candidate.content.parts:
                    if hasattr(part, "text"):
                        text += part.text

                if text.strip():
                    return text

        # Check finish reason
        finish_reason = "UNKNOWN"

        if hasattr(response, "candidates") and response.candidates:
            finish_reason = str(
                response.candidates[0].finish_reason
            )

        return f"""
Errors:
Gemini returned an empty response.

Warnings:
None

Root Cause:
No response was generated by Gemini.

Finish Reason:
{finish_reason}

Recommended Fix:
Retry the request or reduce prompt size.

PIPELINE_STATUS: FAIL
"""

    except Exception as e:
        return f"""
Errors:
{str(e)}

Warnings:
None

Root Cause:
Gemini API request failed.

Recommended Fix:
Check API key, quota, network connectivity, or model availability.

PIPELINE_STATUS: FAIL
"""


# =========================
# GROQ SUPPORT
# =========================
def ask_groq(prompt):
    from groq import Groq

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        return None

    try:
        client = Groq(api_key=api_key)

        completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            model="llama-3.1-8b-instant"
        )

        return completion.choices[0].message.content

    except Exception as e:
        return f"""
Errors:
{str(e)}

Warnings:
None

Root Cause:
Groq API request failed.

Recommended Fix:
Check API key or model availability.

PIPELINE_STATUS: FAIL
"""


# =========================
# AI ROUTER
# =========================
def ask_ai(prompt):

    gemini_key = os.getenv("GEMINI_API_KEY")

    if gemini_key:
        print("🤖 Using Gemini AI")

        result = ask_gemini(prompt)

        if result:
            return result

    groq_key = os.getenv("GROQ_API_KEY")

    if groq_key:
        print("⚡ Using Groq AI")

        result = ask_groq(prompt)

        if result:
            return result

    raise Exception(
        "❌ No valid AI provider available. "
        "Set GEMINI_API_KEY or GROQ_API_KEY."
    )
